defaultBranch: 'development'
branches:
  - label: feature
    name: development
    prefix: feature/
    prTarget: development
  - label: enhancement
    name: development
    prefix: enhancement/
    prTarget: development
  - label: bug
    name: development
    prefix: bugfix/
    prTarget: development
  - label: hotfix
    name: development
    prefix: hotfix/
    prTarget: development
  - label: documentation
    name: documentation
    prefix: doc/
    prTarget: documentation
branchName: '${issue.number}-${issue.title}'
openDraftPR: true
autoCloseIssue: true
